apiVersion: v2
appVersion: 1.3.0
description: A Helm chart for sending k8s logs to Logic Monitor
home: https://logicmonitor.github.io/helm-charts
icon: https://logicmonitor.github.io/helm-charts/lm_logo.png
maintainers:
- email: dev@logicmonitor.com
  name: LogicMonitor
name: lm-logs
version: 0.7.0
