# This rule is not used by the project logicmonitor-openshift-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the monitoring.logicmonitor.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: logicmonitor-openshift-operator
    app.kubernetes.io/managed-by: kustomize
  name: lmcontainer-editor-role
rules:
- apiGroups:
  - monitoring.logicmonitor.com
  resources:
  - lmcontainers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.logicmonitor.com
  resources:
  - lmcontainers/status
  verbs:
  - get
