# Description: ClusterRoleBinding for LogicMonitor SCC usage.
# Description: Binds the scc-user role to the operator controller manager.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: logicmonitor-scc-user-binding
  labels:
    app.kubernetes.io/name: logicmonitor-operator
    app.kubernetes.io/part-of: logicmonitor-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: logicmonitor-scc-user
subjects:
  - kind: ServiceAccount
    name: controller-manager
    namespace: system
