# Description: Kustomize configuration for sample LMContainer resources.
# Description: Includes all sample CRs and credential Secret template.
## Append samples of your project ##
resources:
- monitoring_v1alpha1_lmcontainer.yaml
- monitoring_v1alpha1_lmcontainer_minimal.yaml
- monitoring_v1alpha1_lmcontainer_full.yaml
- monitoring_v1alpha1_lmcontainer_openshift.yaml
- monitoring_v1alpha1_lmcontainer_rosa_advanced.yaml
- secret_lm-credentials.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
