# Description: Kustomization for OpenShift-specific resources.
# Description: Include this overlay for OpenShift deployments.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - scc.yaml
